import type { ImportErrorCode } from "./import-coordinator";
import type { ImportStage } from "@/workers/import-protocol";

export const importCopy = {
  label: "Импорт Markdown-файла",
  chooseFile: "Выбрать файл",
  description: "Выберите один файл .md. Он останется только в этом браузере.",
  selectedFile: "Выбран",
  cancel: "Отменить",
  cancelling: "Отменяем импорт…",
  cancelled: "Импорт отменён.",
  succeeded: "Документ готов.",
  open: "Открыть",
  done: "Готово",
  retry: "Повторить",
  close: "Закрыть",
  title: "Импорт Markdown-файла",
  runningHint: "Отмена завершится без изменений в библиотеке.",
  noPartial: "Готовые документы в библиотеке не изменены.",
  stages: {
    validating: "Проверяем файл…",
    processing: "Обрабатываем Markdown…",
    staging: "Сохраняем части документа…",
    finalizing: "Завершаем импорт…",
  } as const satisfies Record<ImportStage, string>,
  errors: {
    MULTIPLE_FILES: "Выберите ровно один файл .md.",
    UNSUPPORTED_EXTENSION: "Выберите файл с расширением .md.",
    FILE_TOO_LARGE: "Файл слишком большой.",
    INVALID_UTF8: "Файл должен быть в UTF-8.",
    PIPELINE_FAILED: "Не удалось безопасно обработать Markdown-файл.",
    PIPELINE_LIMIT: "Структура Markdown-файла превышает безопасный предел.",
    PROTOCOL_MISMATCH: "Версии приложения несовместимы. Перезагрузите страницу.",
    WORKER_CRASH: "Обработка прервана. Попробуйте снова.",
    CANCELLED: "Импорт отменён.",
    DB_UNAVAILABLE: "Локальное хранилище недоступно.",
    MIGRATION_FAILED: "Не удалось обновить хранилище.",
    STALE_DERIVED: "Документ требует переобработки.",
    QUOTA_EXCEEDED: "Не хватает места в хранилище.",
    COMMIT_CONFLICT: "Документ изменился в другой вкладке.",
    DOCUMENT_NOT_FOUND: "Документ не найден.",
    INVALID_PERSISTED_RECORD: "Данные хранилища повреждены.",
    UNKNOWN_STORAGE_ERROR: "Не удалось сохранить документ.",
  } as const satisfies Record<ImportErrorCode | "MULTIPLE_FILES", string>,
} as const;
