export const readerCopy = {
  continueReading: "Продолжить отсюда",
  applyingSettings: "Применяем настройки чтения…",
  continuousMode: "Непрерывное чтение",
  nextPart: "Следующая часть раздела",
  nextSection: "Следующий раздел",
  openSettings: "Открыть настройки чтения",
  previousPart: "Предыдущая часть раздела",
  previousSection: "Предыдущий раздел",
  persistenceFailed: "Не удалось автоматически сохранить место чтения. Документ остаётся доступен; попробуем снова при следующем перемещении.",
  readingProgress: "Прогресс чтения",
  readingMode: "Режим чтения",
  sectionContext: "Раздел {current} из {total} — {title}",
  sectionNavigation: "Навигация по разделам",
  sectionWindowNavigation: "Навигация внутри раздела",
  sectionsMode: "По разделам",
  settings: "Настройки чтения",
  settingsDescription: "Выберите способ представления документа. Внутренние безопасные фрагменты сохраняются всегда.",
  settingsFailed: "Не удалось применить настройки; прежний вариант сохранён.",
  restoreApproximate: "Место чтения восстановлено приблизительно. Можно продолжить отсюда или начать сначала.",
  restoreNotFound: "Сохранённое место чтения не найдено. Документ открыт с начала.",
  splitStrategy: "Стратегия разделения",
  strategies: { auto: "Автоматически", h1: "По H1", h2: "По H2", h3: "По H3", whole: "Весь документ" },
  strategyContinuousHint: "Стратегия сохраняется и будет применена в режиме разделов.",
  strategyHint: "Стратегия определяет разделы; безопасные внутренние фрагменты не отключаются.",
  startReading: "Начать сначала",
  untitledSection: "Без названия",
  wholeRecommendation: "Рекомендуем автоматическую стратегию.",
  wholeUnavailable: "Весь документ недоступен для выбора: размер раздела превышает безопасный бюджет.",
} as const;
